version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test-db
    ports:
      - '5432:5432'